# This workflow builds and deploys a Jekyll site to GitHub Pages,
# manually installing Ruby 3.1.4 using ruby-build into $RUNNER_TOOL_CACHE.

name: Deploy Jekyll site to Pages 2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install system dependencies for ruby-build and Ruby
      - name: Install dependencies for ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential libssl-dev libreadline-dev zlib1g-dev

      # Step 3: Clone ruby-build, install it, and then use it to install Ruby 3.1.4
      - name: Install ruby-build and Ruby 3.1.4
        run: |
          # Clone ruby-build
          git clone https://github.com/rbenv/ruby-build.git
          cd ruby-build
          # Install ruby-build into /usr/local (adjust PREFIX if needed)
          sudo PREFIX=/usr/local ./install.sh
          cd ..
          # Use ruby-build to install Ruby 3.1.4 into the runner’s tool cache
          ruby-build 3.1.4 "$RUNNER_TOOL_CACHE/Ruby/3.1.4/x64"
          # Mark the installation as complete
          touch "$RUNNER_TOOL_CACHE/Ruby/3.1.4/x64.complete"

      # Step 4: Verify the Ruby installation
      - name: Verify Ruby installation
        run: ruby -v

      # Step 5: Install Bundler and project dependencies
      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install

      # Step 6: Setup GitHub Pages (configuration step)
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      # Step 7: Build the site using Jekyll
      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      # Step 8: Upload the built site as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
